run_name: OLMo-1B-dev
seed: 6198
dry_run: false

# wandb:
#   name: ${run_name}
#   project: olmo

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: true  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 4.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_overwrite: false
# Sharded checkpoints (best for restarts)
save_interval: 100
save_num_checkpoints_to_keep: 11
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 1000
save_num_unsharded_checkpoints_to_keep: -1

load_path: /mnt/nas/hoyeon/OLMo/official_checkpoints/1b/step50000-unsharded

max_duration: 739_328  # 3.1T tokens
global_train_batch_size: 2048
device_train_microbatch_size: 4

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

eval_interval: 999999999999
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators: []

# inject_indices_map: '/mnt/nas/hoyeon/OLMo/analysis/inject_indices_map/5000050100.pkl'
inject_indices_map: /mnt/nas/hoyeon/OLMo/analysis/inject_indices_map/50000-50005.pkl
data_shuffling: true

data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  paths:
    - /mnt/nas/jinho/data/OLMo-1B/part-000-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-000-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-001-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-002-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-003-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-004-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-004-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-005-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-005-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-006-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-006-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-007-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-008-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-008-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-009-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-009-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-010-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-010-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-011-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-012-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-013-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-014-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-015-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-016-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-017-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-017-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-018-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-018-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-019-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-020-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-020-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-021-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-022-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-023-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-024-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-025-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-025-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-026-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-026-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-027-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-027-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-028-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-029-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-030-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-031-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-032-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-033-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-033-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-034-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-034-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-035-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-035-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-036-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-036-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-037-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-038-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-039-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-039-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-040-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-041-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-042-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-043-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-044-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-045-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-045-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-046-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-047-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-047-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-048-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-049-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-050-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-051-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-052-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-053-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-054-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-055-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-056-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-057-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-058-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-059-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-060-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-061-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-062-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-063-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-064-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-064-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-065-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-065-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-066-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-066-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-067-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-067-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-068-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-068-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-069-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-069-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-070-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-071-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-072-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-073-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-074-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-074-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-075-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-075-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-076-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-076-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-077-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-078-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-078-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-079-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-079-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-080-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-081-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-082-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-083-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-083-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-084-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-085-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-086-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-087-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-088-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-088-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-089-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-089-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-090-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-090-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-091-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-092-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-093-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-094-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-095-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-096-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-096-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-097-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-098-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-099-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-100-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-101-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-102-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-102-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-103-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-104-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-105-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-105-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-106-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-107-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-108-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-109-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-110-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-111-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-112-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-112-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-113-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-114-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-115-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-116-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-117-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-118-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-118-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-119-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-120-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-120-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-121-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-122-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-123-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-124-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-125-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-126-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-126-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-127-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-128-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-129-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-130-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-131-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-132-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-133-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-134-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-135-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-136-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-137-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-138-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-139-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-139-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-140-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-141-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-142-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-143-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-143-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-144-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-145-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-145-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-146-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-147-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-147-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-148-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-149-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-149-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-150-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-151-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-151-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-152-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-152-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-153-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-153-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-154-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-155-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-156-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-156-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-157-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-158-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-158-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-159-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-160-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-160-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-161-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-161-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-162-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-163-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-163-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-164-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-165-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-165-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-166-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-166-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-167-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-167-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-168-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-169-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-170-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-171-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-172-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-173-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-174-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-174-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-175-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-176-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-177-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-178-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-179-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-179-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-180-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-181-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-182-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-183-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-184-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-185-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-185-00001.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-186-00000.npy
    - /mnt/nas/jinho/data/OLMo-1B/part-187-00000.npy